Update the sentinel image;
This adds netcat for a new `wait_for_server` function which counts
down for 10 minutes while the first Server boots up leveraging the
SERVICE variable to construct the host and hard-codes the default port.

diff --git a/custom_images/redis-3.2/sentinel/k8s-redis-ha-sentinel b/custom_images/redis-3.2/sentinel/k8s-redis-ha-sentinel
--- a/custom_images/redis-3.2/sentinel/k8s-redis-ha-sentinel
+++ b/custom_images/redis-3.2/sentinel/k8s-redis-ha-sentinel
@@ -6,6 +6,24 @@ namespace="$(< /var/run/secrets/kubernetes.io/serviceaccount/namespace)"
 readonly namespace
 readonly service_domain="_$SERVICE_PORT._tcp.$SERVICE.$namespace.svc.cluster.local"
 
+server_host="${SERVICE}.default"
+server_port="6379" # Default Redis Server Port
+
+wait_for_server () {
+  counter=120
+  until [ $counter -le 0 ]
+  do
+    if [[ ! $(nc -z "${server_host}" "${server_port}") ]]
+    then
+      let counter-=1
+      sleep 5
+    else
+      return 0
+    fi
+  done
+  return 1
+}
+
 redis_info () {
   set +e
   timeout 10 redis-cli -h "$1" -a "$REDIS_PASSWORD" info replication
@@ -66,4 +84,11 @@ run () {
   exec docker-entrypoint.sh redis-sentinel "$@"
 }
 
-run "$@"
+if wait_for_server
+then
+  run "$@"
+else
+  echo "Failed to wait for Redis Server."
+  exit 1
+fi
+
